// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/while-act/hackathon-backend/ent/equipment"
	"github.com/while-act/hackathon-backend/ent/history"
	"github.com/while-act/hackathon-backend/ent/predicate"
)

// EquipmentUpdate is the builder for updating Equipment entities.
type EquipmentUpdate struct {
	config
	hooks    []Hook
	mutation *EquipmentMutation
}

// Where appends a list predicates to the EquipmentUpdate builder.
func (eu *EquipmentUpdate) Where(ps ...predicate.Equipment) *EquipmentUpdate {
	eu.mutation.Where(ps...)
	return eu
}

// SetAvgPriceDol sets the "avg_price_dol" field.
func (eu *EquipmentUpdate) SetAvgPriceDol(f float64) *EquipmentUpdate {
	eu.mutation.ResetAvgPriceDol()
	eu.mutation.SetAvgPriceDol(f)
	return eu
}

// AddAvgPriceDol adds f to the "avg_price_dol" field.
func (eu *EquipmentUpdate) AddAvgPriceDol(f float64) *EquipmentUpdate {
	eu.mutation.AddAvgPriceDol(f)
	return eu
}

// SetAvgPriceRub sets the "avg_price_rub" field.
func (eu *EquipmentUpdate) SetAvgPriceRub(f float64) *EquipmentUpdate {
	eu.mutation.ResetAvgPriceRub()
	eu.mutation.SetAvgPriceRub(f)
	return eu
}

// AddAvgPriceRub adds f to the "avg_price_rub" field.
func (eu *EquipmentUpdate) AddAvgPriceRub(f float64) *EquipmentUpdate {
	eu.mutation.AddAvgPriceRub(f)
	return eu
}

// AddHistoryIDs adds the "histories" edge to the History entity by IDs.
func (eu *EquipmentUpdate) AddHistoryIDs(ids ...string) *EquipmentUpdate {
	eu.mutation.AddHistoryIDs(ids...)
	return eu
}

// AddHistories adds the "histories" edges to the History entity.
func (eu *EquipmentUpdate) AddHistories(h ...*History) *EquipmentUpdate {
	ids := make([]string, len(h))
	for i := range h {
		ids[i] = h[i].ID
	}
	return eu.AddHistoryIDs(ids...)
}

// Mutation returns the EquipmentMutation object of the builder.
func (eu *EquipmentUpdate) Mutation() *EquipmentMutation {
	return eu.mutation
}

// ClearHistories clears all "histories" edges to the History entity.
func (eu *EquipmentUpdate) ClearHistories() *EquipmentUpdate {
	eu.mutation.ClearHistories()
	return eu
}

// RemoveHistoryIDs removes the "histories" edge to History entities by IDs.
func (eu *EquipmentUpdate) RemoveHistoryIDs(ids ...string) *EquipmentUpdate {
	eu.mutation.RemoveHistoryIDs(ids...)
	return eu
}

// RemoveHistories removes "histories" edges to History entities.
func (eu *EquipmentUpdate) RemoveHistories(h ...*History) *EquipmentUpdate {
	ids := make([]string, len(h))
	for i := range h {
		ids[i] = h[i].ID
	}
	return eu.RemoveHistoryIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (eu *EquipmentUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, eu.sqlSave, eu.mutation, eu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (eu *EquipmentUpdate) SaveX(ctx context.Context) int {
	affected, err := eu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (eu *EquipmentUpdate) Exec(ctx context.Context) error {
	_, err := eu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (eu *EquipmentUpdate) ExecX(ctx context.Context) {
	if err := eu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (eu *EquipmentUpdate) check() error {
	if v, ok := eu.mutation.AvgPriceDol(); ok {
		if err := equipment.AvgPriceDolValidator(v); err != nil {
			return &ValidationError{Name: "avg_price_dol", err: fmt.Errorf(`ent: validator failed for field "Equipment.avg_price_dol": %w`, err)}
		}
	}
	if v, ok := eu.mutation.AvgPriceRub(); ok {
		if err := equipment.AvgPriceRubValidator(v); err != nil {
			return &ValidationError{Name: "avg_price_rub", err: fmt.Errorf(`ent: validator failed for field "Equipment.avg_price_rub": %w`, err)}
		}
	}
	return nil
}

func (eu *EquipmentUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := eu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(equipment.Table, equipment.Columns, sqlgraph.NewFieldSpec(equipment.FieldID, field.TypeString))
	if ps := eu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := eu.mutation.AvgPriceDol(); ok {
		_spec.SetField(equipment.FieldAvgPriceDol, field.TypeFloat64, value)
	}
	if value, ok := eu.mutation.AddedAvgPriceDol(); ok {
		_spec.AddField(equipment.FieldAvgPriceDol, field.TypeFloat64, value)
	}
	if value, ok := eu.mutation.AvgPriceRub(); ok {
		_spec.SetField(equipment.FieldAvgPriceRub, field.TypeFloat64, value)
	}
	if value, ok := eu.mutation.AddedAvgPriceRub(); ok {
		_spec.AddField(equipment.FieldAvgPriceRub, field.TypeFloat64, value)
	}
	if eu.mutation.HistoriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   equipment.HistoriesTable,
			Columns: []string{equipment.HistoriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(history.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := eu.mutation.RemovedHistoriesIDs(); len(nodes) > 0 && !eu.mutation.HistoriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   equipment.HistoriesTable,
			Columns: []string{equipment.HistoriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(history.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := eu.mutation.HistoriesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   equipment.HistoriesTable,
			Columns: []string{equipment.HistoriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(history.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, eu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{equipment.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	eu.mutation.done = true
	return n, nil
}

// EquipmentUpdateOne is the builder for updating a single Equipment entity.
type EquipmentUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *EquipmentMutation
}

// SetAvgPriceDol sets the "avg_price_dol" field.
func (euo *EquipmentUpdateOne) SetAvgPriceDol(f float64) *EquipmentUpdateOne {
	euo.mutation.ResetAvgPriceDol()
	euo.mutation.SetAvgPriceDol(f)
	return euo
}

// AddAvgPriceDol adds f to the "avg_price_dol" field.
func (euo *EquipmentUpdateOne) AddAvgPriceDol(f float64) *EquipmentUpdateOne {
	euo.mutation.AddAvgPriceDol(f)
	return euo
}

// SetAvgPriceRub sets the "avg_price_rub" field.
func (euo *EquipmentUpdateOne) SetAvgPriceRub(f float64) *EquipmentUpdateOne {
	euo.mutation.ResetAvgPriceRub()
	euo.mutation.SetAvgPriceRub(f)
	return euo
}

// AddAvgPriceRub adds f to the "avg_price_rub" field.
func (euo *EquipmentUpdateOne) AddAvgPriceRub(f float64) *EquipmentUpdateOne {
	euo.mutation.AddAvgPriceRub(f)
	return euo
}

// AddHistoryIDs adds the "histories" edge to the History entity by IDs.
func (euo *EquipmentUpdateOne) AddHistoryIDs(ids ...string) *EquipmentUpdateOne {
	euo.mutation.AddHistoryIDs(ids...)
	return euo
}

// AddHistories adds the "histories" edges to the History entity.
func (euo *EquipmentUpdateOne) AddHistories(h ...*History) *EquipmentUpdateOne {
	ids := make([]string, len(h))
	for i := range h {
		ids[i] = h[i].ID
	}
	return euo.AddHistoryIDs(ids...)
}

// Mutation returns the EquipmentMutation object of the builder.
func (euo *EquipmentUpdateOne) Mutation() *EquipmentMutation {
	return euo.mutation
}

// ClearHistories clears all "histories" edges to the History entity.
func (euo *EquipmentUpdateOne) ClearHistories() *EquipmentUpdateOne {
	euo.mutation.ClearHistories()
	return euo
}

// RemoveHistoryIDs removes the "histories" edge to History entities by IDs.
func (euo *EquipmentUpdateOne) RemoveHistoryIDs(ids ...string) *EquipmentUpdateOne {
	euo.mutation.RemoveHistoryIDs(ids...)
	return euo
}

// RemoveHistories removes "histories" edges to History entities.
func (euo *EquipmentUpdateOne) RemoveHistories(h ...*History) *EquipmentUpdateOne {
	ids := make([]string, len(h))
	for i := range h {
		ids[i] = h[i].ID
	}
	return euo.RemoveHistoryIDs(ids...)
}

// Where appends a list predicates to the EquipmentUpdate builder.
func (euo *EquipmentUpdateOne) Where(ps ...predicate.Equipment) *EquipmentUpdateOne {
	euo.mutation.Where(ps...)
	return euo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (euo *EquipmentUpdateOne) Select(field string, fields ...string) *EquipmentUpdateOne {
	euo.fields = append([]string{field}, fields...)
	return euo
}

// Save executes the query and returns the updated Equipment entity.
func (euo *EquipmentUpdateOne) Save(ctx context.Context) (*Equipment, error) {
	return withHooks(ctx, euo.sqlSave, euo.mutation, euo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (euo *EquipmentUpdateOne) SaveX(ctx context.Context) *Equipment {
	node, err := euo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (euo *EquipmentUpdateOne) Exec(ctx context.Context) error {
	_, err := euo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (euo *EquipmentUpdateOne) ExecX(ctx context.Context) {
	if err := euo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (euo *EquipmentUpdateOne) check() error {
	if v, ok := euo.mutation.AvgPriceDol(); ok {
		if err := equipment.AvgPriceDolValidator(v); err != nil {
			return &ValidationError{Name: "avg_price_dol", err: fmt.Errorf(`ent: validator failed for field "Equipment.avg_price_dol": %w`, err)}
		}
	}
	if v, ok := euo.mutation.AvgPriceRub(); ok {
		if err := equipment.AvgPriceRubValidator(v); err != nil {
			return &ValidationError{Name: "avg_price_rub", err: fmt.Errorf(`ent: validator failed for field "Equipment.avg_price_rub": %w`, err)}
		}
	}
	return nil
}

func (euo *EquipmentUpdateOne) sqlSave(ctx context.Context) (_node *Equipment, err error) {
	if err := euo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(equipment.Table, equipment.Columns, sqlgraph.NewFieldSpec(equipment.FieldID, field.TypeString))
	id, ok := euo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Equipment.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := euo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, equipment.FieldID)
		for _, f := range fields {
			if !equipment.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != equipment.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := euo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := euo.mutation.AvgPriceDol(); ok {
		_spec.SetField(equipment.FieldAvgPriceDol, field.TypeFloat64, value)
	}
	if value, ok := euo.mutation.AddedAvgPriceDol(); ok {
		_spec.AddField(equipment.FieldAvgPriceDol, field.TypeFloat64, value)
	}
	if value, ok := euo.mutation.AvgPriceRub(); ok {
		_spec.SetField(equipment.FieldAvgPriceRub, field.TypeFloat64, value)
	}
	if value, ok := euo.mutation.AddedAvgPriceRub(); ok {
		_spec.AddField(equipment.FieldAvgPriceRub, field.TypeFloat64, value)
	}
	if euo.mutation.HistoriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   equipment.HistoriesTable,
			Columns: []string{equipment.HistoriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(history.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := euo.mutation.RemovedHistoriesIDs(); len(nodes) > 0 && !euo.mutation.HistoriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   equipment.HistoriesTable,
			Columns: []string{equipment.HistoriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(history.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := euo.mutation.HistoriesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   equipment.HistoriesTable,
			Columns: []string{equipment.HistoriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(history.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Equipment{config: euo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, euo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{equipment.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	euo.mutation.done = true
	return _node, nil
}
