// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/while-act/hackathon-backend/ent/history"
	"github.com/while-act/hackathon-backend/ent/industry"
	"github.com/while-act/hackathon-backend/ent/predicate"
)

// IndustryQuery is the builder for querying Industry entities.
type IndustryQuery struct {
	config
	ctx           *QueryContext
	order         []industry.OrderOption
	inters        []Interceptor
	predicates    []predicate.Industry
	withHistories *HistoryQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the IndustryQuery builder.
func (iq *IndustryQuery) Where(ps ...predicate.Industry) *IndustryQuery {
	iq.predicates = append(iq.predicates, ps...)
	return iq
}

// Limit the number of records to be returned by this query.
func (iq *IndustryQuery) Limit(limit int) *IndustryQuery {
	iq.ctx.Limit = &limit
	return iq
}

// Offset to start from.
func (iq *IndustryQuery) Offset(offset int) *IndustryQuery {
	iq.ctx.Offset = &offset
	return iq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (iq *IndustryQuery) Unique(unique bool) *IndustryQuery {
	iq.ctx.Unique = &unique
	return iq
}

// Order specifies how the records should be ordered.
func (iq *IndustryQuery) Order(o ...industry.OrderOption) *IndustryQuery {
	iq.order = append(iq.order, o...)
	return iq
}

// QueryHistories chains the current query on the "histories" edge.
func (iq *IndustryQuery) QueryHistories() *HistoryQuery {
	query := (&HistoryClient{config: iq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := iq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := iq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(industry.Table, industry.FieldID, selector),
			sqlgraph.To(history.Table, history.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, industry.HistoriesTable, industry.HistoriesColumn),
		)
		fromU = sqlgraph.SetNeighbors(iq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Industry entity from the query.
// Returns a *NotFoundError when no Industry was found.
func (iq *IndustryQuery) First(ctx context.Context) (*Industry, error) {
	nodes, err := iq.Limit(1).All(setContextOp(ctx, iq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{industry.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (iq *IndustryQuery) FirstX(ctx context.Context) *Industry {
	node, err := iq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Industry ID from the query.
// Returns a *NotFoundError when no Industry ID was found.
func (iq *IndustryQuery) FirstID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = iq.Limit(1).IDs(setContextOp(ctx, iq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{industry.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (iq *IndustryQuery) FirstIDX(ctx context.Context) string {
	id, err := iq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Industry entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Industry entity is found.
// Returns a *NotFoundError when no Industry entities are found.
func (iq *IndustryQuery) Only(ctx context.Context) (*Industry, error) {
	nodes, err := iq.Limit(2).All(setContextOp(ctx, iq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{industry.Label}
	default:
		return nil, &NotSingularError{industry.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (iq *IndustryQuery) OnlyX(ctx context.Context) *Industry {
	node, err := iq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Industry ID in the query.
// Returns a *NotSingularError when more than one Industry ID is found.
// Returns a *NotFoundError when no entities are found.
func (iq *IndustryQuery) OnlyID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = iq.Limit(2).IDs(setContextOp(ctx, iq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{industry.Label}
	default:
		err = &NotSingularError{industry.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (iq *IndustryQuery) OnlyIDX(ctx context.Context) string {
	id, err := iq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Industries.
func (iq *IndustryQuery) All(ctx context.Context) ([]*Industry, error) {
	ctx = setContextOp(ctx, iq.ctx, "All")
	if err := iq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Industry, *IndustryQuery]()
	return withInterceptors[[]*Industry](ctx, iq, qr, iq.inters)
}

// AllX is like All, but panics if an error occurs.
func (iq *IndustryQuery) AllX(ctx context.Context) []*Industry {
	nodes, err := iq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Industry IDs.
func (iq *IndustryQuery) IDs(ctx context.Context) (ids []string, err error) {
	if iq.ctx.Unique == nil && iq.path != nil {
		iq.Unique(true)
	}
	ctx = setContextOp(ctx, iq.ctx, "IDs")
	if err = iq.Select(industry.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (iq *IndustryQuery) IDsX(ctx context.Context) []string {
	ids, err := iq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (iq *IndustryQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, iq.ctx, "Count")
	if err := iq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, iq, querierCount[*IndustryQuery](), iq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (iq *IndustryQuery) CountX(ctx context.Context) int {
	count, err := iq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (iq *IndustryQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, iq.ctx, "Exist")
	switch _, err := iq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (iq *IndustryQuery) ExistX(ctx context.Context) bool {
	exist, err := iq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the IndustryQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (iq *IndustryQuery) Clone() *IndustryQuery {
	if iq == nil {
		return nil
	}
	return &IndustryQuery{
		config:        iq.config,
		ctx:           iq.ctx.Clone(),
		order:         append([]industry.OrderOption{}, iq.order...),
		inters:        append([]Interceptor{}, iq.inters...),
		predicates:    append([]predicate.Industry{}, iq.predicates...),
		withHistories: iq.withHistories.Clone(),
		// clone intermediate query.
		sql:  iq.sql.Clone(),
		path: iq.path,
	}
}

// WithHistories tells the query-builder to eager-load the nodes that are connected to
// the "histories" edge. The optional arguments are used to configure the query builder of the edge.
func (iq *IndustryQuery) WithHistories(opts ...func(*HistoryQuery)) *IndustryQuery {
	query := (&HistoryClient{config: iq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	iq.withHistories = query
	return iq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		AvgWorkersNum float64 `json:"avg_workers_num,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Industry.Query().
//		GroupBy(industry.FieldAvgWorkersNum).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (iq *IndustryQuery) GroupBy(field string, fields ...string) *IndustryGroupBy {
	iq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &IndustryGroupBy{build: iq}
	grbuild.flds = &iq.ctx.Fields
	grbuild.label = industry.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		AvgWorkersNum float64 `json:"avg_workers_num,omitempty"`
//	}
//
//	client.Industry.Query().
//		Select(industry.FieldAvgWorkersNum).
//		Scan(ctx, &v)
func (iq *IndustryQuery) Select(fields ...string) *IndustrySelect {
	iq.ctx.Fields = append(iq.ctx.Fields, fields...)
	sbuild := &IndustrySelect{IndustryQuery: iq}
	sbuild.label = industry.Label
	sbuild.flds, sbuild.scan = &iq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a IndustrySelect configured with the given aggregations.
func (iq *IndustryQuery) Aggregate(fns ...AggregateFunc) *IndustrySelect {
	return iq.Select().Aggregate(fns...)
}

func (iq *IndustryQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range iq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, iq); err != nil {
				return err
			}
		}
	}
	for _, f := range iq.ctx.Fields {
		if !industry.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if iq.path != nil {
		prev, err := iq.path(ctx)
		if err != nil {
			return err
		}
		iq.sql = prev
	}
	return nil
}

func (iq *IndustryQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Industry, error) {
	var (
		nodes       = []*Industry{}
		_spec       = iq.querySpec()
		loadedTypes = [1]bool{
			iq.withHistories != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Industry).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Industry{config: iq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, iq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := iq.withHistories; query != nil {
		if err := iq.loadHistories(ctx, query, nodes,
			func(n *Industry) { n.Edges.Histories = []*History{} },
			func(n *Industry, e *History) { n.Edges.Histories = append(n.Edges.Histories, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (iq *IndustryQuery) loadHistories(ctx context.Context, query *HistoryQuery, nodes []*Industry, init func(*Industry), assign func(*Industry, *History)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[string]*Industry)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(history.FieldIndustryBranch)
	}
	query.Where(predicate.History(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(industry.HistoriesColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.IndustryBranch
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "industry_branch" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (iq *IndustryQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := iq.querySpec()
	_spec.Node.Columns = iq.ctx.Fields
	if len(iq.ctx.Fields) > 0 {
		_spec.Unique = iq.ctx.Unique != nil && *iq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, iq.driver, _spec)
}

func (iq *IndustryQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(industry.Table, industry.Columns, sqlgraph.NewFieldSpec(industry.FieldID, field.TypeString))
	_spec.From = iq.sql
	if unique := iq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if iq.path != nil {
		_spec.Unique = true
	}
	if fields := iq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, industry.FieldID)
		for i := range fields {
			if fields[i] != industry.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := iq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := iq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := iq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := iq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (iq *IndustryQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(iq.driver.Dialect())
	t1 := builder.Table(industry.Table)
	columns := iq.ctx.Fields
	if len(columns) == 0 {
		columns = industry.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if iq.sql != nil {
		selector = iq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if iq.ctx.Unique != nil && *iq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range iq.predicates {
		p(selector)
	}
	for _, p := range iq.order {
		p(selector)
	}
	if offset := iq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := iq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// IndustryGroupBy is the group-by builder for Industry entities.
type IndustryGroupBy struct {
	selector
	build *IndustryQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (igb *IndustryGroupBy) Aggregate(fns ...AggregateFunc) *IndustryGroupBy {
	igb.fns = append(igb.fns, fns...)
	return igb
}

// Scan applies the selector query and scans the result into the given value.
func (igb *IndustryGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, igb.build.ctx, "GroupBy")
	if err := igb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*IndustryQuery, *IndustryGroupBy](ctx, igb.build, igb, igb.build.inters, v)
}

func (igb *IndustryGroupBy) sqlScan(ctx context.Context, root *IndustryQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(igb.fns))
	for _, fn := range igb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*igb.flds)+len(igb.fns))
		for _, f := range *igb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*igb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := igb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// IndustrySelect is the builder for selecting fields of Industry entities.
type IndustrySelect struct {
	*IndustryQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (is *IndustrySelect) Aggregate(fns ...AggregateFunc) *IndustrySelect {
	is.fns = append(is.fns, fns...)
	return is
}

// Scan applies the selector query and scans the result into the given value.
func (is *IndustrySelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, is.ctx, "Select")
	if err := is.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*IndustryQuery, *IndustrySelect](ctx, is.IndustryQuery, is, is.inters, v)
}

func (is *IndustrySelect) sqlScan(ctx context.Context, root *IndustryQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(is.fns))
	for _, fn := range is.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*is.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := is.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
