// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/while-act/hackathon-backend/ent/history"
	"github.com/while-act/hackathon-backend/ent/predicate"
	"github.com/while-act/hackathon-backend/ent/taxationsystem"
)

// TaxationSystemQuery is the builder for querying TaxationSystem entities.
type TaxationSystemQuery struct {
	config
	ctx           *QueryContext
	order         []taxationsystem.OrderOption
	inters        []Interceptor
	predicates    []predicate.TaxationSystem
	withHistories *HistoryQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the TaxationSystemQuery builder.
func (tsq *TaxationSystemQuery) Where(ps ...predicate.TaxationSystem) *TaxationSystemQuery {
	tsq.predicates = append(tsq.predicates, ps...)
	return tsq
}

// Limit the number of records to be returned by this query.
func (tsq *TaxationSystemQuery) Limit(limit int) *TaxationSystemQuery {
	tsq.ctx.Limit = &limit
	return tsq
}

// Offset to start from.
func (tsq *TaxationSystemQuery) Offset(offset int) *TaxationSystemQuery {
	tsq.ctx.Offset = &offset
	return tsq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (tsq *TaxationSystemQuery) Unique(unique bool) *TaxationSystemQuery {
	tsq.ctx.Unique = &unique
	return tsq
}

// Order specifies how the records should be ordered.
func (tsq *TaxationSystemQuery) Order(o ...taxationsystem.OrderOption) *TaxationSystemQuery {
	tsq.order = append(tsq.order, o...)
	return tsq
}

// QueryHistories chains the current query on the "histories" edge.
func (tsq *TaxationSystemQuery) QueryHistories() *HistoryQuery {
	query := (&HistoryClient{config: tsq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := tsq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := tsq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(taxationsystem.Table, taxationsystem.FieldID, selector),
			sqlgraph.To(history.Table, history.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, taxationsystem.HistoriesTable, taxationsystem.HistoriesColumn),
		)
		fromU = sqlgraph.SetNeighbors(tsq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first TaxationSystem entity from the query.
// Returns a *NotFoundError when no TaxationSystem was found.
func (tsq *TaxationSystemQuery) First(ctx context.Context) (*TaxationSystem, error) {
	nodes, err := tsq.Limit(1).All(setContextOp(ctx, tsq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{taxationsystem.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (tsq *TaxationSystemQuery) FirstX(ctx context.Context) *TaxationSystem {
	node, err := tsq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first TaxationSystem ID from the query.
// Returns a *NotFoundError when no TaxationSystem ID was found.
func (tsq *TaxationSystemQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = tsq.Limit(1).IDs(setContextOp(ctx, tsq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{taxationsystem.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (tsq *TaxationSystemQuery) FirstIDX(ctx context.Context) int {
	id, err := tsq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single TaxationSystem entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one TaxationSystem entity is found.
// Returns a *NotFoundError when no TaxationSystem entities are found.
func (tsq *TaxationSystemQuery) Only(ctx context.Context) (*TaxationSystem, error) {
	nodes, err := tsq.Limit(2).All(setContextOp(ctx, tsq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{taxationsystem.Label}
	default:
		return nil, &NotSingularError{taxationsystem.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (tsq *TaxationSystemQuery) OnlyX(ctx context.Context) *TaxationSystem {
	node, err := tsq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only TaxationSystem ID in the query.
// Returns a *NotSingularError when more than one TaxationSystem ID is found.
// Returns a *NotFoundError when no entities are found.
func (tsq *TaxationSystemQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = tsq.Limit(2).IDs(setContextOp(ctx, tsq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{taxationsystem.Label}
	default:
		err = &NotSingularError{taxationsystem.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (tsq *TaxationSystemQuery) OnlyIDX(ctx context.Context) int {
	id, err := tsq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of TaxationSystems.
func (tsq *TaxationSystemQuery) All(ctx context.Context) ([]*TaxationSystem, error) {
	ctx = setContextOp(ctx, tsq.ctx, "All")
	if err := tsq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*TaxationSystem, *TaxationSystemQuery]()
	return withInterceptors[[]*TaxationSystem](ctx, tsq, qr, tsq.inters)
}

// AllX is like All, but panics if an error occurs.
func (tsq *TaxationSystemQuery) AllX(ctx context.Context) []*TaxationSystem {
	nodes, err := tsq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of TaxationSystem IDs.
func (tsq *TaxationSystemQuery) IDs(ctx context.Context) (ids []int, err error) {
	if tsq.ctx.Unique == nil && tsq.path != nil {
		tsq.Unique(true)
	}
	ctx = setContextOp(ctx, tsq.ctx, "IDs")
	if err = tsq.Select(taxationsystem.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (tsq *TaxationSystemQuery) IDsX(ctx context.Context) []int {
	ids, err := tsq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (tsq *TaxationSystemQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, tsq.ctx, "Count")
	if err := tsq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, tsq, querierCount[*TaxationSystemQuery](), tsq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (tsq *TaxationSystemQuery) CountX(ctx context.Context) int {
	count, err := tsq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (tsq *TaxationSystemQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, tsq.ctx, "Exist")
	switch _, err := tsq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (tsq *TaxationSystemQuery) ExistX(ctx context.Context) bool {
	exist, err := tsq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the TaxationSystemQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (tsq *TaxationSystemQuery) Clone() *TaxationSystemQuery {
	if tsq == nil {
		return nil
	}
	return &TaxationSystemQuery{
		config:        tsq.config,
		ctx:           tsq.ctx.Clone(),
		order:         append([]taxationsystem.OrderOption{}, tsq.order...),
		inters:        append([]Interceptor{}, tsq.inters...),
		predicates:    append([]predicate.TaxationSystem{}, tsq.predicates...),
		withHistories: tsq.withHistories.Clone(),
		// clone intermediate query.
		sql:  tsq.sql.Clone(),
		path: tsq.path,
	}
}

// WithHistories tells the query-builder to eager-load the nodes that are connected to
// the "histories" edge. The optional arguments are used to configure the query builder of the edge.
func (tsq *TaxationSystemQuery) WithHistories(opts ...func(*HistoryQuery)) *TaxationSystemQuery {
	query := (&HistoryClient{config: tsq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	tsq.withHistories = query
	return tsq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Usn6 float64 `json:"usn6,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.TaxationSystem.Query().
//		GroupBy(taxationsystem.FieldUsn6).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (tsq *TaxationSystemQuery) GroupBy(field string, fields ...string) *TaxationSystemGroupBy {
	tsq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &TaxationSystemGroupBy{build: tsq}
	grbuild.flds = &tsq.ctx.Fields
	grbuild.label = taxationsystem.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Usn6 float64 `json:"usn6,omitempty"`
//	}
//
//	client.TaxationSystem.Query().
//		Select(taxationsystem.FieldUsn6).
//		Scan(ctx, &v)
func (tsq *TaxationSystemQuery) Select(fields ...string) *TaxationSystemSelect {
	tsq.ctx.Fields = append(tsq.ctx.Fields, fields...)
	sbuild := &TaxationSystemSelect{TaxationSystemQuery: tsq}
	sbuild.label = taxationsystem.Label
	sbuild.flds, sbuild.scan = &tsq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a TaxationSystemSelect configured with the given aggregations.
func (tsq *TaxationSystemQuery) Aggregate(fns ...AggregateFunc) *TaxationSystemSelect {
	return tsq.Select().Aggregate(fns...)
}

func (tsq *TaxationSystemQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range tsq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, tsq); err != nil {
				return err
			}
		}
	}
	for _, f := range tsq.ctx.Fields {
		if !taxationsystem.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if tsq.path != nil {
		prev, err := tsq.path(ctx)
		if err != nil {
			return err
		}
		tsq.sql = prev
	}
	return nil
}

func (tsq *TaxationSystemQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*TaxationSystem, error) {
	var (
		nodes       = []*TaxationSystem{}
		_spec       = tsq.querySpec()
		loadedTypes = [1]bool{
			tsq.withHistories != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*TaxationSystem).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &TaxationSystem{config: tsq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, tsq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := tsq.withHistories; query != nil {
		if err := tsq.loadHistories(ctx, query, nodes,
			func(n *TaxationSystem) { n.Edges.Histories = []*History{} },
			func(n *TaxationSystem, e *History) { n.Edges.Histories = append(n.Edges.Histories, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (tsq *TaxationSystemQuery) loadHistories(ctx context.Context, query *HistoryQuery, nodes []*TaxationSystem, init func(*TaxationSystem), assign func(*TaxationSystem, *History)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*TaxationSystem)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(history.FieldTaxationSystemOperations)
	}
	query.Where(predicate.History(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(taxationsystem.HistoriesColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.TaxationSystemOperations
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "taxation_system_operations" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (tsq *TaxationSystemQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := tsq.querySpec()
	_spec.Node.Columns = tsq.ctx.Fields
	if len(tsq.ctx.Fields) > 0 {
		_spec.Unique = tsq.ctx.Unique != nil && *tsq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, tsq.driver, _spec)
}

func (tsq *TaxationSystemQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(taxationsystem.Table, taxationsystem.Columns, sqlgraph.NewFieldSpec(taxationsystem.FieldID, field.TypeInt))
	_spec.From = tsq.sql
	if unique := tsq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if tsq.path != nil {
		_spec.Unique = true
	}
	if fields := tsq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, taxationsystem.FieldID)
		for i := range fields {
			if fields[i] != taxationsystem.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := tsq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := tsq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := tsq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := tsq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (tsq *TaxationSystemQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(tsq.driver.Dialect())
	t1 := builder.Table(taxationsystem.Table)
	columns := tsq.ctx.Fields
	if len(columns) == 0 {
		columns = taxationsystem.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if tsq.sql != nil {
		selector = tsq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if tsq.ctx.Unique != nil && *tsq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range tsq.predicates {
		p(selector)
	}
	for _, p := range tsq.order {
		p(selector)
	}
	if offset := tsq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := tsq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// TaxationSystemGroupBy is the group-by builder for TaxationSystem entities.
type TaxationSystemGroupBy struct {
	selector
	build *TaxationSystemQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (tsgb *TaxationSystemGroupBy) Aggregate(fns ...AggregateFunc) *TaxationSystemGroupBy {
	tsgb.fns = append(tsgb.fns, fns...)
	return tsgb
}

// Scan applies the selector query and scans the result into the given value.
func (tsgb *TaxationSystemGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, tsgb.build.ctx, "GroupBy")
	if err := tsgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*TaxationSystemQuery, *TaxationSystemGroupBy](ctx, tsgb.build, tsgb, tsgb.build.inters, v)
}

func (tsgb *TaxationSystemGroupBy) sqlScan(ctx context.Context, root *TaxationSystemQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(tsgb.fns))
	for _, fn := range tsgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*tsgb.flds)+len(tsgb.fns))
		for _, f := range *tsgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*tsgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := tsgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// TaxationSystemSelect is the builder for selecting fields of TaxationSystem entities.
type TaxationSystemSelect struct {
	*TaxationSystemQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (tss *TaxationSystemSelect) Aggregate(fns ...AggregateFunc) *TaxationSystemSelect {
	tss.fns = append(tss.fns, fns...)
	return tss
}

// Scan applies the selector query and scans the result into the given value.
func (tss *TaxationSystemSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, tss.ctx, "Select")
	if err := tss.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*TaxationSystemQuery, *TaxationSystemSelect](ctx, tss.TaxationSystemQuery, tss, tss.inters, v)
}

func (tss *TaxationSystemSelect) sqlScan(ctx context.Context, root *TaxationSystemQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(tss.fns))
	for _, fn := range tss.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*tss.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := tss.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
