// Code generated by ent, DO NOT EDIT.

package equipment

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/while-act/hackathon-backend/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.Equipment {
	return predicate.Equipment(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.Equipment {
	return predicate.Equipment(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.Equipment {
	return predicate.Equipment(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.Equipment {
	return predicate.Equipment(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.Equipment {
	return predicate.Equipment(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.Equipment {
	return predicate.Equipment(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.Equipment {
	return predicate.Equipment(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.Equipment {
	return predicate.Equipment(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.Equipment {
	return predicate.Equipment(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.Equipment {
	return predicate.Equipment(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.Equipment {
	return predicate.Equipment(sql.FieldContainsFold(FieldID, id))
}

// AvgPriceRub applies equality check predicate on the "avg_price_rub" field. It's identical to AvgPriceRubEQ.
func AvgPriceRub(v float64) predicate.Equipment {
	return predicate.Equipment(sql.FieldEQ(FieldAvgPriceRub, v))
}

// AvgPriceRubEQ applies the EQ predicate on the "avg_price_rub" field.
func AvgPriceRubEQ(v float64) predicate.Equipment {
	return predicate.Equipment(sql.FieldEQ(FieldAvgPriceRub, v))
}

// AvgPriceRubNEQ applies the NEQ predicate on the "avg_price_rub" field.
func AvgPriceRubNEQ(v float64) predicate.Equipment {
	return predicate.Equipment(sql.FieldNEQ(FieldAvgPriceRub, v))
}

// AvgPriceRubIn applies the In predicate on the "avg_price_rub" field.
func AvgPriceRubIn(vs ...float64) predicate.Equipment {
	return predicate.Equipment(sql.FieldIn(FieldAvgPriceRub, vs...))
}

// AvgPriceRubNotIn applies the NotIn predicate on the "avg_price_rub" field.
func AvgPriceRubNotIn(vs ...float64) predicate.Equipment {
	return predicate.Equipment(sql.FieldNotIn(FieldAvgPriceRub, vs...))
}

// AvgPriceRubGT applies the GT predicate on the "avg_price_rub" field.
func AvgPriceRubGT(v float64) predicate.Equipment {
	return predicate.Equipment(sql.FieldGT(FieldAvgPriceRub, v))
}

// AvgPriceRubGTE applies the GTE predicate on the "avg_price_rub" field.
func AvgPriceRubGTE(v float64) predicate.Equipment {
	return predicate.Equipment(sql.FieldGTE(FieldAvgPriceRub, v))
}

// AvgPriceRubLT applies the LT predicate on the "avg_price_rub" field.
func AvgPriceRubLT(v float64) predicate.Equipment {
	return predicate.Equipment(sql.FieldLT(FieldAvgPriceRub, v))
}

// AvgPriceRubLTE applies the LTE predicate on the "avg_price_rub" field.
func AvgPriceRubLTE(v float64) predicate.Equipment {
	return predicate.Equipment(sql.FieldLTE(FieldAvgPriceRub, v))
}

// HasHistories applies the HasEdge predicate on the "histories" edge.
func HasHistories() predicate.Equipment {
	return predicate.Equipment(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, HistoriesTable, HistoriesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasHistoriesWith applies the HasEdge predicate on the "histories" edge with a given conditions (other predicates).
func HasHistoriesWith(preds ...predicate.History) predicate.Equipment {
	return predicate.Equipment(func(s *sql.Selector) {
		step := newHistoriesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Equipment) predicate.Equipment {
	return predicate.Equipment(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Equipment) predicate.Equipment {
	return predicate.Equipment(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Equipment) predicate.Equipment {
	return predicate.Equipment(func(s *sql.Selector) {
		p(s.Not())
	})
}
